# Generated by Django 5.2.11 on 2026-03-27 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_profile_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
