# Generated by Django 5.2.11 on 2026-04-03 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='auction',
            name='suspension_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='auction',
            name='suspension_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
